name: Release

on:
  push:
    branches: master

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      RELATIVE_CI_KEY: ${{ secrets.RELATIVE_CI_KEY }}
    steps:
      - name: Release Build
        run: pnpm build
